apiVersion: v1
kind: Service
metadata:
    name: "rvek8"
    labels:
        app: "rvek8"
spec:
    type: ClusterIP
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "rvek8"