on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n rvearc1 -g rvearc1a602-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n rvearc1 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n rvearc1 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n rvearc1 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: rvearc1.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/guestbook-go" -f  "guestbook-go/Dockerfile" -t rvearc1.azurecr.io/rvek8:${{ github.sha }}
        docker push rvearc1.azurecr.io/rvek8:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_rvek8_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rvek8ebdb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rvek8ebdb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rvek8ebdb
        container-registry-url: rvearc1.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: rvek8dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: rvek8ebdb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          rvearc1.azurecr.io/rvek8:${{ github.sha }}
        imagepullsecrets: |
          rvek8dockerauth